name:
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install packages
        run: pnpm ci
      - name: Lint
        run: pnpm run ling

