name:
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install packages
        run: npm run install
      - name: Lint
        run: npm run lint
  test_ui:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install packages
        run: npm run install
      - name: Lint
        run: npm run test

